# Generated by Django 2.2.4 on 2020-01-12 17:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPage',
            new_name='HomePage',
        ),
        migrations.RenameModel(
            old_name='PostPage',
            new_name='SitePage',
        ),
    ]
